trigger:
- feature/*

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: 'Prepare'
  jobs:
  - job: 'PrepareSonarcloudEnvironment'
    steps:
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'sonarcloud'
        organization: 'pahofmann-gitlab'
        scannerMode: 'CLI'
        configMode: 'file'
- stage: 'Unit Test'
  jobs:
  - job: 'categoryService'
    steps:
    - task: Gradle@1
      inputs:
        gradleWrapperFile: 'gradlew' 
        workingDirectory: '$(Build.SourcesDirectory)/backend/category-service/'
        tasks: 'clean test'
        publishJUnitResults: true 
        testResultsFiles: '$(Build.SourcesDirectory)/backend/category-service/build/reports/jacoco/test/jacocoTestReport.xml'
        codeCoverageToolOption: 'jaCoCo'
        codeCoverageClassFilesDirectories: '$(Build.SourcesDirectory)/backend/category-service/build/classes/main/'
        sonarQubeRunAnalysis: false
- stage: sonar-scan
  jobs:
  - job: 'categoryService'
    steps:
    - task: SonarCloudAnalyze@1
- stage: Compile
  jobs:
  - job: 'categoryService'
    steps:
    - task: Gradle@2
      inputs:
        gradleWrapperFile: 'gradlew'
        workingDirectory: '$(Build.SourcesDirectory)/backend/category-service/'
        tasks: 'build'
        publishJUnitResults: false
        sonarQubeRunAnalysis: false

