trigger:
- feature/*

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: 'Unit_Test'
  jobs:
  - job: 'category_service'
    steps:
    - task: Gradle@1
      displayName: category service
      inputs:
        gradleWrapperFile: 'gradlew'
        workingDirectory: '$(Build.SourcesDirectory)/backend/category-service/'
        tasks: 'clean test jacocoTestReport'
        publishJUnitResults: false
        sonarQubeRunAnalysis: false
    - task: PublishCodeCoverageResults@1
      displayName: Publish Coverage Results
      inputs:
        codeCoverageTool: 'JaCoCo'
        summaryFileLocation: '**/build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml'
        reportDirectory: '**/build/reports/jacoco/jacocoRootReport/html'
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'sonarcloud'
        organization: 'pahofmann-gitlab'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'budgt-category-service'
        cliProjectName: 'budgt-category-service'
        cliSources: 'backend/category-service/src/main/java'
        extraProperties: |
          sonar.core.codeCoveragePlugin=jacoco
          sonar.coverage.jacoco.xmlReportPaths=backend/category-service/build/reports/jacoco/test/jacocoTestReport.xml
          sonar.jacoco.reportPath=backend/category-service/build/jacoco/test.exec
          sonar.dynamicAnalysis=reuseReports
          sonar.java.binaries=backend/category-service/build/classes/
    - task: SonarCloudAnalyze@1

