trigger:
- feature/*

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: 'Unit_Test'
  jobs:
  - job: 'category_service'
    steps:
    - task: Gradle@1
      displayName: category service
      inputs:
        gradleWrapperFile: 'gradlew'
        workingDirectory: '$(Build.SourcesDirectory)/backend/category-service/'
        tasks: 'clean test jacocoTestReport'
        publishJUnitResults: false
        sonarQubeRunAnalysis: false
    - task: PublishCodeCoverageResults@1
      displayName: Publish Coverage Results
      inputs:
        codeCoverageTool: 'JaCoCo'
        summaryFileLocation: '**/build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml'
        reportDirectory: '**/build/reports/jacoco/jacocoRootReport/html'
- stage: sonar_scan
  jobs:
  - job: 'category_service'
    steps:
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'sonarcloud'
        organization: 'pahofmann-gitlab'
        scannerMode: 'CLI'
        configMode: 'file'
        configFile: '/home/vsts/work/1/s/budgt/backend/category-service/sonar-project.properties'
    - task: SonarCloudAnalyze@1
- stage: Compile
  jobs:
  - job: 'category_service'
    steps:
    - task: Gradle@2
      inputs:
        gradleWrapperFile: 'gradlew'
        workingDirectory: '$(Build.SourcesDirectory)/backend/category-service/'
        tasks: 'build'
        publishJUnitResults: false
        sonarQubeRunAnalysis: false

