# Use root/example as user/password credentials
version: "3.7"

services:
  budgt-frontend:
    image: budgt/budgt-frontend:edge
    restart: always
    container_name: budgt-frontend
    networks:
      budgt-network:
        aliases:
          - budgt-frontend
    ports:
      - 80:80
      - 443:443
    volumes:
      - /opt/budgt/certs/:/opt/budgt/certs/
      - /home/patrick/git/budgt/frontend/build/deploy/conf/local/nginx.conf:/etc/nginx/nginx.conf
    healthcheck:
      test: ["CMD", "curl", "-f", "https://dev.budgt.de"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  budgt-category-service:
    image: budgt-category-service
    restart: always
    container_name: budgt-category-service
    depends_on:
      - budgt-config-server
      - budgt-mongodb
    networks:
      budgt-network:
        aliases:
          - budgt-category-service
    ports:
      - 1338:1338
    healthcheck:
      test:
        ["CMD", "curl", "-f", "http://budgt-category-service:1338/categories"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  budgt-config-server:
    image: budgt/budgt-config-server:edge
    restart: always
    container_name: budgt-config-server
    networks:
      budgt-network:
        aliases:
          - budgt-config-server
    volumes:
      - /opt/budgt-configuration:/opt/budgt-configuration
    ports:
      - 1339:1339

    healthcheck:
      test:
        ["CMD", "curl", "-f", "http://budgt-config-server:1339/actuator/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  budgt-mongodb:
    image: mongo:xenial
    restart: always
    container_name: budgt-mongodb
    networks:
      budgt-network:
        aliases:
          - budgt-mongodb
    volumes:
      - /opt/docker/mongodb/data:/data/db
    ports:
      - 27017:27017
    command: mongod --auth

networks:
  budgt-network:
    external:
      name: budgt-network
