# Use root/example as user/password credentials
version: "3.7"

services:
  budgt-gateway:
    image: budgt-gateway:latest
    restart: always
    container_name: budgt-gateway
    depends_on:
      - budgt-config-server
    networks:
      budgt-network:
        aliases:
          - budgt-gateway
    ports:
      - 80:1336
    environment:
      - "SPRING_PROFILES_ACTIVE=local"

  budgt-frontend:
    image: budgt-frontend:latest
    restart: always
    container_name: budgt-frontend
    networks:
      budgt-network:
        aliases:
          - budgt-frontend
    ports:
      - 1380:1380

  budgt-category-service:
    image: budgt-category-service:latest
    restart: always
    container_name: budgt-category-service
    depends_on:
      - budgt-config-server
      - budgt-mongodb
    networks:
      budgt-network:
        aliases:
          - budgt-category-service
    ports:
      - 1338:1338
    environment:
      - "SPRING_PROFILES_ACTIVE=local"

  budgt-config-server:
    image: budgt-config-server:latest
    restart: always
    container_name: budgt-config-server
    networks:
      budgt-network:
        aliases:
          - budgt-config-server
    ports:
      - 1339:1339
    volumes:
      - /opt/budgt-configuration:/opt/budgt-configuration

  budgt-mongodb:
    image: mongo:xenial
    restart: always
    container_name: budgt-mongodb
    networks:
      budgt-network:
        aliases:
          - budgt-mongodb
    volumes:
      - /opt/docker/mongodb/data:/data/db
    command: mongod --auth

networks:
  budgt-network:
    external:
      name: budgt-network
