version: "3.7"

services:
  budgt-gateway:
    image: budgt-gateway:latest
    restart: always
    container_name: budgt-gateway
    depends_on:
      - budgt-config-server
    networks:
      budgt-network:
        aliases:
          - budgt-gateway
    ports:
      - 80:1336
    environment:
      - "SPRING_PROFILES_ACTIVE=local"

  budgt-frontend:
    image: budgt-frontend:latest
    restart: always
    container_name: budgt-frontend
    networks:
      budgt-network:
        aliases:
          - budgt-frontend
    ports:
      - 1380:1380

  budgt-category-service:
    image: budgt-category-service:latest
    restart: always
    container_name: budgt-category-service
    depends_on:
      - budgt-config-server
      - budgt-mongodb
    networks:
      budgt-network:
        aliases:
          - budgt-category-service
    ports:
      - 1338:1338
    environment:
      - "SPRING_PROFILES_ACTIVE=local"

  budgt-bank-account-service:
    image: budgt/budgt-bank-account-service:latest
    restart: always
    container_name: budgt-bank-account-service
    depends_on:
      - budgt-config-server
      - budgt-mongodb
    networks:
      budgt-network:
        aliases:
          - budgt-bank-account-service-service
    ports:
      - 1350:1350
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"

  budgt-banking-connector:
    image: budgt/budgt-banking-connector:latest
    restart: always
    container_name: budgt-banking-connector
    depends_on:
      - budgt-config-server
      - budgt-mongodb
    networks:
      budgt-network:
        aliases:
          - budgt-banking-connector-service
    ports:
      - 1351:1351
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"

  budgt-config-server:
    image: budgt-config-server:latest
    restart: always
    container_name: budgt-config-server
    networks:
      budgt-network:
        aliases:
          - budgt-config-server
    ports:
      - 1339:1339
    volumes:
      - /opt/budgt-configuration:/opt/budgt-configuration

  budgt-registry-service:
    image: budgt-registry-service:latest
    restart: always
    container_name: budgt-registry-service
    networks:
      budgt-network:
        aliases:
          - budgt-registry-service
    ports:
      - 1340:1340
    environment:
      - "SPRING_PROFILES_ACTIVE=local"
    depends_on:
      - budgt-config-server

  budgt-auth-service:
    image: budgt-auth-service:latest
    restart: always
    container_name: budgt-auth-service
    networks:
      budgt-network:
        aliases:
          - budgt-auth-service
    ports:
      - 1331:1331
    environment:
      - "SPRING_PROFILES_ACTIVE=local"
    depends_on:
      - budgt-config-server

  budgt-account-service:
    image: budgt-account-service:latest
    restart: always
    container_name: budgt-account-service
    networks:
      budgt-network:
        aliases:
          - budgt-account-service
    ports:
      - 1332:1332
    environment:
      - "SPRING_PROFILES_ACTIVE=local"
    depends_on:
      - budgt-config-server

  budgt-mongodb:
    image: mongo:xenial
    restart: always
    container_name: budgt-mongodb
    networks:
      budgt-network:
        aliases:
          - budgt-mongodb
    volumes:
      - /opt/docker/mongodb/data:/data/db
    command: mongod --auth

networks:
  budgt-network:
    external:
      name: budgt-network
